### ISSUE TITLE
Hotspot Baisc implement

### ISSUE THREAD

**Issue by AkideLiu** [UAws/COVID_contact_tracing_system#51]
<s> - [ ] 热点地区, 根据check-in人数决定，如果user再次check-in那个地点就会有warning弹窗,暴露地点 </s>
- [x] 同时，热点地区以彩色板块的形式展现在地图上
- [x] Admin/Health Official可以改变热点地区

**Comment by Anzhu-W** [comment]
以Venue为单位, 定一个合适大小的半径, 红色的圆圈来表示. (分三个等级)
1. admin: 点击Modify按钮, 随后需要输入Venue id或者名称关键词,  进行热点地区的增删改

- 首先，admin进入venue table页面，对venue进行搜寻，然后通过点击not in/in hotspot按钮也可以对hotspot进行增或删，但是无法更改暴露地点等级。（***此时，既然我们以venue为单位，则可以将这两个按钮的名字改成is/not hotspot）
![WechatIMG236](https://user-images.githubusercontent.com/65104474/120828897-37670300-c59c-11eb-9d9e-9c585a331966.png)

- 然后，Admin 在 fronted-admin 进入一个新的页面—— ”Modify Hotspot“ 页面（该页面限制user等级，只有admin可以访问，如果有其他等级的用户试图访问，则显示access denied）。 

- 该页面中，一侧引用google map，更详细的向admin展示venue名称；另一侧以表格形式列出目前所有已添加的Hotspots（也就是包括在venue table中被选为is in hotspot的venue）

- 在此页面中，admin可以通过点击相应按钮（not in hotspots；modify）对这些hotspot进行删除和修改操作。

- 通过点击not in hotspots/remove按钮：将相应venue移除。

- 通过点击modify按钮， 有下拉框显示危险等级，以红橙黄三种颜色的圈来表示不同危险等级的hotspot。

![WechatIMG239](https://user-images.githubusercontent.com/65104474/120829479-9a589a00-c59c-11eb-945f-7407e8371386.jpeg)

**Comment by Ziqi222** [comment]
1. User的check-in 页面: 

>左侧菜单栏， 新建一级菜单，叫Check-in。该页面顶端有一个输入框，用来输入check-in code, 点右边的check-in button就可以成功check in。  check-in code 对应的地址可以直接显示在下面的map里。 

>输入框下面，是地图，一侧引用google map, 用红色坐标的样子；
另一侧以表格形式更详细的展示user 所check in 的venue名称,地址和时间。
（可以直接套用hotspot模版，红色坐标不好实现的话，就直接用圆点表示）。
右侧列表，有显示框，显示user check-in的地址是否在hotspot。
![image](https://user-images.githubusercontent.com/64782437/120896172-82961a00-c65f-11eb-84a3-353e1c4de946.png)
![image](https://user-images.githubusercontent.com/64782437/120898037-621e8d80-c668-11eb-92d6-1a653c5e38d4.png)

2.  Venue的view check-in history页面: 

> 此页面需要显示每个vunue里的user check-in history(有哪些user在此地check-in 过)
按照Table里，Permission那种表格框架的模板：展现user的ID,名字，时间，电话。
![image](https://user-images.githubusercontent.com/64782437/120896836-65167f80-c662-11eb-888f-4370e2885a8e.png)
![image](https://user-images.githubusercontent.com/64782437/120897822-36e76e80-c667-11eb-8dee-a303b4fe529a.png)


3，Admin view check-in history页面: 

> 输入框要输入关键字，即可得到想要的user check-in信息。
（比如，输入框输入用户id，即可展现此用户所check的信息；输入框输入商家地址或名字, 即可展现哪些user在此商家check-in 过）
与venue的check-in history table相似，在展现user的ID,名字，时间，电话的基础上，添加venue的名字与地址。
![image](https://user-images.githubusercontent.com/64782437/120897919-c1c86900-c667-11eb-9628-6f4eb2281686.png)

**Comment by AkideLiu** [comment]
<img width="1586" alt="2021-06-06_02-45-23" src="https://user-images.githubusercontent.com/41593290/120899929-3f44a700-c671-11eb-80ec-94bb65e5fd05.png">

- [x] HotSpot Map Frontend
- [x] HotSpot data persistence
- [x] HotSpot backedn controller

HotSpot could be add or change by hotspot page, admins/ officials also could change the risk level based on different venue

See https://github.com/UAws/COVID_contact_tracing_system/pull/53
