### ISSUE TITLE
This criterion is linked to a Learning OutcomeCheck-In and Hotspot Implementation

### ISSUE THREAD

**Issue by AkideLiu** [UAws/COVID_contact_tracing_system#66]
- [x] A user can easily and seamlessly check in and view their history and hotspots. 
- [x] Venue Managers can easily view check-in history for their venue. 
- [x] Admins/Health Officials can easily and seamlessly manage hotspots and view check-ins for users and venues.

**Comment by AkideLiu** [comment]
Review for A user can easily and seamlessly check in and view their history and hotspots.
<img width="2304" alt="2021-06-11_18-49-20" src="https://user-images.githubusercontent.com/41593290/121663691-d54f5600-cae5-11eb-9fba-f084ee119129.png">
<img width="2304" alt="2021-06-11_18-49-37" src="https://user-images.githubusercontent.com/41593290/121663719-dc766400-cae5-11eb-9ffd-cb1ad12f98df.png">

**Comment by Ziqi222** [comment]
![Screenshot (2)](https://user-images.githubusercontent.com/64782437/121671875-4135bc80-caee-11eb-9b5e-45d4cb2fb92f.png)
