### ISSUE TITLE
This criterion is linked to a Learning Outcome Database schema

### ISSUE THREAD

**Issue by Ziqi222** [UAws/COVID_contact_tracing_system#73]
- [x] Your database schema & queries should be in the form of a plain-text .sql file containing the CREATE TABLE statements of the schema, and your draft queries.
- [ ] A backup of your final database.

**Comment by AkideLiu** [comment]
The SQL on database server are daily backuped and raw database backup could be found by following link : https://github.com/UAws/COVID_contact_tracing_system/blob/master/backend/sql_dump/dump.sql
