### ISSUE TITLE
Fantistic Project

### ISSUE THREAD

**Issue by a1779748** [UAws/COVID_contact_tracing_system#84]
Actually, there are no real issues. The reason I'm here is that I really want to give a :thumbsup: to this project. As well as making friends :satisfied:.

Due to the time constrain and lack of communication with my group members, I could not able to finish all features of my group project. Therefore I really want to learn something from your group. If possible could I have your WeChat Qrcode @AkideLiu?

**Comment by AkideLiu** [comment]
Greatly appreciate your positive feedback. 

As the github is a public platform i may not able to share Wechat QRCode here, however i will contact you shortly via wechat WDC group. : )
